### ISSUE TITLE
vaInitialize fails under Gnome Shell Wayland

### ISSUE THREAD

**Issue by vanvugt** [intel/libva#79] opened 2017-06-29 07:45 UTC
vaInitialize fails when Xwayland is running. So VA-API never works at all in Gnome Shell on Wayland.

It appears the problem is libva only supports DRI2. And Xwayland only supports DRI3.

I understand you could call this a bug in the video player apps for not choosing native wayland first, but this problem is prevalent in every single video player app that supports VA-API I have encountered (gst-play-1.0, totem, mpv). So trying to fix each video player isn't really a solution that scales (also my first attempt at doing so was rejected by mpv).

**Comment by chivakker** [comment] 2017-09-20 02:48
Did you compile libva and intel-vaapi-driver with Wayland support?

**Comment by stuarta** [comment] 2017-09-20 08:50
@chivakker  I'm seeing what looks like this issue with the stock libva shipped with fedora 26 (libva-1.8.3-1.fc26.x86_64), and the corresponding libva-intel-driver from rpmfusion (libva-intel-driver-1.8.3-2.fc26.x86_64).

I raised https://bugzilla.redhat.com/show_bug.cgi?id=1491186 for fedora, and we have done some investigation there, there is also a simplified reproducer.

Regards
Stuart

**Comment by vanvugt** [comment] 2017-09-22 01:23
I did not compile libva. Just using the standard Ubuntu installation. We have it working now, including Wayland.

The problem and the solution are both detailed in the first comment already, so you might want to read that...

For Ubuntu what we did to work around the issue was to prioritize Wayland over X11 in both mpv and gstreamer-opengl (to aid gstreamer-vaapi). So that way video players don't attempt to use X11 with Xwayland and then give up. They use native Wayland instead.

**Comment by vanvugt** [comment] 2017-09-22 01:25
The proper solution for libva would be to support DRI3, so that libva doesn't fail when talking to Xwayland.

**Comment by xhaihao** [comment] 2017-09-22 03:16
I filed https://github.com/01org/libva/issues/122 to track the support for DRI3.

**Comment by vanvugt** [comment] 2017-09-23 02:08
While strictly accurate, it might be harsh and unnecessary for me to suggest libva needs DRI3 support.

Ubuntu doesn't need that any more. What I said does not scale is in fact what we have now done as a workaround. And really even in a world where libva supported DRI3, I still think these "workarounds" for mpv and gstreamer-vaapi are in fact along the lines of what player apps should be doing. They don't have to prioritize Wayland over X11, but they should be flexible enough to at least try libva with Wayland if X11 has already failed to init. The assumption that there's only one windowing system present is the real mistake because in the world of Xwayland (always present for Gnome Shell) it's no longer true.

**Comment by realh** [comment] 2018-01-29 22:24
Unofficial packages of Chromium with VAAPI enabled exist for at least Ubuntu and Arch, and the patch may be made official, but that still doesn't work with Wayland. Linux desperately needs a decent browser with hardware-accelerated video, and this issue could block that for many users.

**Comment by jnettlet** [comment] 2018-06-11 05:56
I have been testing these patches on my Intel based laptop.  Chromium running under XWayland sees significant stuttering when using DRI3 and Present.  I assume this is happening because XWayland 1.20 now supports double buffering.  I will follow up with some logs when I dig into this deeper.

**Comment by realh** [comment] 2018-06-11 11:46
@jnettlet That could be because of <https://bugs.freedesktop.org/show_bug.cgi?id=106841>.

**Comment by jnettlet** [comment] 2018-06-11 12:49
@realh thanks for the heads up.  I have been tracking most the open bugs on these various issues.  Tested that patch earlier today and that fixes the drawing corruption I was seeing but not the frame jumping and repeating.  I attempted to run Chrome with vertical sync disabled and also patched the intel-vaapi-driver to pass the XCB_PRESENT_OPTION_ASYNC option into present to try and completely bypass flipping, however the behaviour did not change.

**Comment by kode54** [comment] 2018-12-17 01:19
This apparently also affects AMDGPU+radeonsi, as I can't get VA-API to enable there in Chromium, either. Or in VLC. VLC manages to initialize VDPAU, though.

**Comment by jnettlet** [comment] 2019-02-10 10:45
Wanted to report back that there has been some progress made regarding the vsync issues with chromium-vaapi under Xwayland.  The patches from this bug, including the callback patchset now have hardware acceleration mostly working for me.  https://gitlab.freedesktop.org/xorg/xserver/issues/631

I have rebased this patchset and the one for the intel-vaapi driver on the latest branches and everything is working.  If the original submitter isn't going to rebase and submit I will send a new pull request since it is now a mostly functioning option, once the rest of this works makes it into Xwayland.

**Comment by intelfx** [comment] 2019-02-11 17:18
@jnettlet I was under impression that currently existing VA-API patches for Chromium never work under Wayland?

**Comment by jnettlet** [comment] 2019-02-11 17:35
@intelfx well Chromium doesn't work directly under Wayland, yet, although Igalia is making a lot of progress.  This is Chromium running under XWayland and specifically, I am running it with gnome-shell wayland as my compositor.  The initial work that @xhaihao did allow Xwayland based apps to use libva for hardware acceleration.  However Chromium because of how it is architected exposed other limitations in the Present infrastructure that needed to be addressed before it was usable.   Direct rendering would work, but Chromium couldn't display it properly because the XWayland Vsync timings were off.  Now we are closer to having those issues closed due to the work done in the Xserver bug I posted above and things are pretty usable now. 

I have run into a couple of crashers that I need to debug, but in general, it is stable enough that I now want to get these patches cleaned up and merged so we can clean up the rest of the pieces.  I think this is even more relevant since more distributions are now providing Chromium with the vaapi patches built.  Fedora 29 now has chromium-vaapi in their repos, Aarch has had it for a while, and I believe there is an Ubuntu PPA that provides it.

I will try and get pull requests for my rebased work submitted this week, I will also include documentation on what I needed to do in order to get Chromium-Vaapi running decently under XWayland.  There has been some discussion on the closed Xserver bug and another bug will be opened to work on this further.

**Comment by jnettlet** [comment] 2019-02-14 15:58
Just a quick follow up.  With the default patchset I was still seeing some misrendering under XWayland in Chromium.  I have fixed most of it so the playback looks solid, but I am still dropping frames occasionally.  This is not choppy video but hitches every 10 seconds or so.  I am assuming this is because the XWayland patches aren't still quite perfect yet.  I also probably need to switch this to use triple buffering in the backend to help matchup video framerate vs vsync.

I will push my branches this weekend and then ask for more testing because I send an actual pull request.

**Comment by sndirsch** [comment] 2019-02-26 11:40
> The patches from this bug, including the callback patchset now have hardware acceleration mostly 
> working for me. https://gitlab.freedesktop.org/xorg/xserver/issues/631

I see a closed issue there, but no patchset?!? I might be too stupid in order to use the gitlab page though. Mabye you can help me to find this patchset?

**Comment by jnettlet** [comment] 2019-02-28 20:21
The main patch to fix that specific bug was merged into the Xwayland
already.  The alternative patchset that was proposed in that bug and is
also needed is,
https://gitlab.freedesktop.org/xorg/xserver/merge_requests/116

This causes a slightly higher cpu usage by gnome-shell, but that is
partially caused because the CPUs are able to stay at a lower clock speed.
This seems to have been fixed in the next release of gnome-shell.

**Comment by dvrogozh** [comment] 2022-09-27 18:18
DRI3 support got added to libva in #614. Please, give it a try and open new issue(s) if needed.

**Closed by dvrogozh** 2022-09-27 18:18 UTC
